### PR TITLE
Update freedesktop to 19.08

### PR DESCRIPTION
**Pull request by A6GibKm**

### CODE REVIEW

**Comment by A6GibKm** [comment]
Fixes #12 and #4.

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by A6GibKm** [comment]
bot, build io.brackets.Brackets

**Comment by A6GibKm** [comment]
Buildbot ran out of space. Will try later.

**Comment by A6GibKm** [comment]
bot, build io.brackets.Brackets

**Comment by bilelmoussaoui** [comment]
Thanks!

**Pull request merged**
